var annotated_dup =
[
    [ "AddSensorDialog", "class_add_sensor_dialog.html", null ],
    [ "AppConfig", "struct_app_config.html", null ],
    [ "ArpScanner", "class_arp_scanner.html", null ],
    [ "AuthenticationDialog", "class_authentication_dialog.html", null ],
    [ "BrokerConfig", "struct_broker_config.html", null ],
    [ "CameraWidget", "class_camera_widget.html", null ],
    [ "DashboardWindow", "class_dashboard_window.html", null ],
    [ "DatabaseManager", "class_database_manager.html", null ],
    [ "KnownRaspberryPi", "struct_known_raspberry_pi.html", null ],
    [ "LoginWidget", "class_login_widget.html", null ],
    [ "MainWindow", "class_main_window.html", null ],
    [ "ModuleInfo", "struct_module_info.html", null ],
    [ "ModuleManager", "class_module_manager.html", null ],
    [ "NetworkDevice", "struct_network_device.html", null ],
    [ "NetworkScannerDialog", "class_network_scanner_dialog.html", null ],
    [ "RaspberryManager", "class_raspberry_manager.html", null ],
    [ "RaspberryNode", "struct_raspberry_node.html", null ],
    [ "ResizableContainer", "class_resizable_container.html", null ],
    [ "ResizeHandle", "class_resize_handle.html", null ],
    [ "SensorConfig", "struct_sensor_config.html", null ],
    [ "SensorFactory", "class_sensor_factory.html", null ],
    [ "SensorInfo", "struct_sensor_info.html", null ],
    [ "SmokeSensorWidget", "class_smoke_sensor_widget.html", null ],
    [ "TemperatureWidget", "class_temperature_widget.html", null ],
    [ "User", "struct_user.html", null ],
    [ "WidgetConfig", "struct_widget_config.html", null ],
    [ "WidgetEditor", "class_widget_editor.html", null ]
];